Story 1.3 olia
minardi/Caesar-Angular pull request #10
Opened 2017-08-13 19:17 UTC by Olga04051995

2017-08-14 08:31 UTC, ksenya-ta requested changes
Good job! Just some minor comments you still need to fix. Also it might be a good idea to write some tests.

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/caesar-portal/group-list/group-list.component.scss
> +  margin-top: 20px;
it is better to combine margins in one block

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/caesar-portal/group-list/group-list.component.scss
> +  border: 1px solid #ccc;
move all colors to variables

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/caesar-portal/group-list/group-list.component.scss
> +  .search-btn {
1 empty line before each new block

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/caesar-portal/group-list/group-item/group-item.component.scss
> +    background-color: #337ab7;
move all colors hashes to variables

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/caesar-portal/group-list/group-item/group-item.component.scss
> +:host{
pls add a space before each curly bracket

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/caesar-portal/common/models/group.ts
> +  experts : string[];
remove extra space here

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/app.component.ts
> +    const body = JSON.stringify({
implement OnInit interface and move this logic to ngOnInit

2017-08-14 08:31 UTC, ksenya-ta commented on src/app/app.component.ts
> +      username: "OlegShvets",
single quotes

2017-08-14 19:37 UTC, Olga04051995 commented
added code fixes , please take a look

2017-08-15 09:51 UTC, ksenya-ta approved these changes

2017-08-15 12:02 UTC, merged