Story 1.3
minardi/Caesar-Angular pull request #5
Opened 2017-08-10 10:16 UTC by tetty2005

- changing common structure;
- add component caesar-portal;
- add 5 components for group-area;

2017-08-10 12:30 UTC, ksenya-ta requested changes
pls update config to use scss before merging anything to dev

2017-08-10 12:30 UTC, ksenya-ta commented on src/app/app.module.ts
> +    GroupAreaComponent,
This is not a correct place for all this declarations, you should define components in the modules that will use it, not the app one

2017-08-10 12:30 UTC, ksenya-ta commented on src/app/caesar-portal/caesar-portal.component.css
> +.app-wrapper {
why css? you should use scss for this project

2017-08-10 12:30 UTC, ksenya-ta commented on src/app/caesar-portal/group-area/group-area.component.html
> +                    <button (click)="onTabChange('info')" type="button" class="btn btn-default" [ngClass]="{active: activeTab === 'info'}">
why are you doing this as tabs? a week ago we agreed that all of this will be separate routes, not tabs

2017-08-11 10:23 UTC, tetty2005 commented
+ update config to use scss
+ add modules for 
+ delete tabs swithing commponents for group-area (routing is in process)

2017-08-11 11:02 UTC, ksenya-ta commented
update build script to ng build --prod -bh ./

2017-08-11 11:02 UTC, ksenya-ta commented on src/app/caesar-portal/group-area/group-area.component.scss
> +	border: 1px solid #ccc;
format your styles, + all colors should be moved to variables so you can reuse them

2017-08-11 11:02 UTC, ksenya-ta commented on package.json
> +    "bootstrap": "^3.3.7",
why not a bootstrap-sass?

2017-08-11 11:23 UTC, ksenya-ta approved these changes

2017-08-11 11:46 UTC, merged